export * from './Home'
export * from './Eco'
export * from './Boletas'
export * from './Empleo'
export * from './Obleas'
export * from './Tramites'
export * from './Noticias'
export * from './Contacto'
